name: pp
description: pp

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_qr_bar_scanner: ^3.0.2
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  floor: ^1.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter


dev_dependencies:
  build_runner: ^2.1.7
  floor_generator: ^1.2.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

